#!/bin/sh

. /etc/ssvconfig/bin/ssvfunction
. /etc/ssvconfig/config/openvpn

#################################
# Set up Ethernet bridge on Linux
# Requires: bridge-utils
#################################
# Define Bridge Interface
br="br0"

# Define list of TAP interfaces to be bridged,
# for example tap="tap0 tap1 tap2".
tap="tap0"

# Define physical ethernet interface to be bridged
# with TAP interface(s) above.
eth="eth0"
	
start()
{
	echo "Starting bridge"
	for t in $tap; do
		openvpn --mktun --dev $t
	done

	modprobe bridge
	brctl addbr $br
	brctl addif $br $eth

	for t in $tap; do
		brctl addif $br $t
	done

	for t in $tap; do
		ifconfig $t 0.0.0.0 promisc up
	done

	ifconfig $eth 0.0.0.0 promisc up

	if [ "x$SSV_OPENVPN_SC" = "xclient" ]; then
		ifconfig $br $SSV_OPENVPN_CLIENT_CBR netmask $SSV_OPENVPN_SERVER_CSUB
	else
		ifconfig $br $SSV_OPENVPN_SERVER_SBR netmask $SSV_OPENVPN_SERVER_CSUB
		if [ "x$SSV_OPENVPN_SERVER_DGW" = "xyes" ]; then
			route add default gw $SSV_OPENVPN_SERVER_GWIP
		fi
	fi
}

stop()
{
	ifconfig $br down
	brctl delbr $br

	for t in $tap; do
		openvpn --rmtun --dev $t
	done
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
