#!/bin/sh
#
# devices       Device handling script. Mounts a ramdisk and create/populate 
#               devices from /etc/device_table list
#
# Version:      1.00  01.03.2009  ene@SSV, based on original
#

. /etc/init.d/functions

g_echo -n "Mounting /dev ramdisk......................................"
mount -t ramfs ramfs /dev || mount -t tmpfs ramfs /dev
[ $? -ne 0 ] && g_echo "failed" || g_echo "done" 

g_echo -n "Populating /dev............................................"
cd /
mkdir -p dev/shm
mkdir -p dev/input
mkdir -p dev/msys
mkdir -p dev/pts
mkdir -p dev/vc
for i in 0 1 2 3 4 5 6 7 8 9; do
    ln -s /dev/tty$i /dev/vc/$i
done
ln -sf /proc/self/fd /dev/fd
ln -sf /proc/kcore /dev/core
/sbin/makedevs -r / -D /etc/device_table
[ $? -ne 0 ] && g_echo "failed" || g_echo "done"

exit 0
